project:
  type: website
  output-dir: docs

website:
  title: "Jeff Oliver"
  navbar:
    left:
      - href: research.qmd
        text: Research
    right: 
      - icon: github
        href: https://github.com/jcoliver
      - icon: twitter
        href: https://twitter.com/jcoliverAZ

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: source
